% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Jan-2016 15:37:12
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('imgs.mat');

images = saveVarsMat.images; % <656x875x2807 double> too many elements

clear saveVarsMat;
